const testTypesActionTypes = {
  START_FETCH_PROFILE:'START_FETCH_PROFILE',
  FETCH_PROFILE_SUCCESS:'FETCH_PROFILE_SUCCESS',
  FETCH_PROFILE_ERROR:'FETCH_PROFILE_ERROR'
};

export default testTypesActionTypes;
