const TestRegistrationActionTypes = {
  REQUEST_TEST_REGISTRATION: 'REQUEST_TEST_REGISTRATION',
  TEST_REGISTRATION_SUCCESS: 'TEST_REGISTRATION_SUCCESS',
  TEST_REGISTRATION_FAILURE: 'TEST_REGISTRATION_FAILURE',

  START_SAVE_FORM:'START_SAVE_FORM',
  COMPLETED_FORM_SUCCESS:'COMPLETED_FORM_SUCCESS',

  START_FETCH_TEST:'START_FETCH_TEST',
  FETCH_TEST_SUCCESS:'FETCH_TEST_SUCCESS'
}

export default TestRegistrationActionTypes
